name: vitrine
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.10.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  http: ^1.2.1
  image_picker: ^1.0.7
  file_picker: ^10.3.7
  shared_preferences: ^2.2.2
  provider: ^6.1.1  # ADICIONE ESTA LINHA

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # fonts:
  #   - family: MaterialIcons
  #     fonts:
  #       - asset: fonts/MaterialIcons-Regular.ttf